### ISSUE TITLE
File "apc-convert.py", line 364, in <module>

### ISSUE THREAD

**Issue by olie93** [ca-za/apc-convert#1]
When i run the script i get the below error:

Traceback (most recent call last):
  File "apc-convert.py", line 364, in <module>
    apc.ca = ovpn.ca
  File "apc-convert.py", line 237, in ca
    if not value.startswith(CERT_START): raise ValueError()
ValueError

**Comment by tomkor** [comment]
The same problem

**Comment by DerVO** [comment]
Same here

**Comment by andreashergert1984** [comment]
me too;

perhaps becaue my openvpn has no client cert/key?..

**Comment by StrannikVK** [comment]
I have same problem, is there a fix?
I check the parameters and my OpenVPN file looks good.
Is there a solution?

**Comment by DaveFH** [comment]
Same  Problem...
tried with python2 und python3

```
Traceback (most recent call last):
  File "apc-convert.py", line 364, in <module>
    apc.ca = ovpn.ca
  File "apc-convert.py", line 237, in ca
    if not value.startswith(CERT_START): raise ValueError()
ValueError
```

**Comment by ca-za** [comment]
Sorry for the late response. The cause of this error is probably the wrong format of the ca certificate. There are plenty of different ways to store certificates and this script is designed to only handle the specific format SOPHOS used around that time. If you provide me your source files then I can maybe build in an workaround.

**Comment by lperezcwcocom** [comment]
was a solution to this ever posted or found?

**Comment by ca-za** [comment]
Unfortunately I can not recreate the problem, otherwise I could maybe solve this.

**Comment by lperezcwcocom** [comment]
this is my command line;
C:\apc-convert-master>apc-convert.py --username aqu020821 --password C0braK@i1931 ovpn2apc aqu.ovpn aqu.apc

the result 👍 
Traceback (most recent call last):
  File "C:\apc-convert-master\apc-convert.py", line 364, in <module>
    apc.ca = ovpn.ca
  File "C:\apc-convert-master\apc-convert.py", line 237, in ca
    if not value.startswith(CERT_START): raise ValueError()
ValueError

the OVPN file contains three certs. The CA, the CERT and the KEY.

**Comment by ca-za** [comment]
thank you, looks like SOPHOS changed the certificate format. I need some time to reproduce this in my lab.

**Comment by bithost** [comment]
Any update on this?

**Comment by ca-za** [comment]
> Any update on this?

unfortunately I could not reproduce this. Can you generate sample files for me?

**Comment by bithost** [comment]
Hey. Sure, what files you want?

**Comment by ca-za** [comment]
just an apc export of an vpn profile. You can simply create a new connection and delete it after the export.

**Comment by fsmeets** [comment]
I just came across this issue when trying to connect a stock OpenVPN to an XG 18.5.1 in S2S mode. Here is a config you can use to adapt the script. Thanks!
[server_test.txt](https://github.com/ca-za/apc-convert/files/7188767/server_test.txt)

I got this working manually, all I had to do after the conversion using the script was to put the -----BEGIN and -----END lines on their own line. The key, cert and ca can be one long line.

**Comment by Phosphenius** [comment]
I managed to fix the script so that it'll output a correctly formatted APC file. Unfortunately, I have no chance to really test it. But feel free to give it a try: https://github.com/Phosphenius/apc-convert

**Comment by speedy01** [comment]
@ca-za Thank you for your work. Unfortunately, I'm having the same error when trying to convert a OVPN to APC as well. I tried with python2 and python3 on linux.  The ovpn file I'm trying to convert is provided by surfshark ( vpn provider).
@Phosphenius  I've tried your modified version, but got a different error.  something like RSA Key format not supported.
